CREATE TABLE ngc2236 (
    starid character varying(25) NOT NULL,
    bv real,
    vmag real DEFAULT 0,
    vmag_err real,
    bmag real DEFAULT 0,
    bmag_err real,
    imag real DEFAULT 0,
    imag_err real,
    u real DEFAULT 0,
    u_err real,
    v real DEFAULT 0,
    v_err real,
    b real DEFAULT 0,
    b_err real,
    y real DEFAULT 0,
    y_err real,
    hbw real DEFAULT 0,
    hbw_err real,
    hbn real DEFAULT 0,
    hbn_err real,
    period real,
    period_err real,
    amp real,
    amp_err real,
    nv integer DEFAULT 0,
    nb integer DEFAULT 0,
    ra double precision,
    dec double precision,
    good boolean,
    member boolean,
    tab integer,
    coord point,
    corotid integer,
    PRIMARY KEY(starid)
);

